name: Deploy GitHub Pages
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install golang
      uses: actions/setup-go@v2
      with:
        go-version: '^1.14.6'
      id: go
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Run Go script
      run: sh script.sh
    - name: Deploy to docs
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'actions@github.com'
        git commit -am 'update docs'
        git push
