name: Deploy GitHub Pages
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install golang
      uses: actions/setup-go@v2
      with:
        go-version: '^1.14.6'
      id: go
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Run Go script
      shell: bash -e {0}
      run: |
        for i in *.csv
        do
            go run .github/workflows/main.go $i
        done
    - name: Deploy to docs
      run: |
        git add -A
        if [[ `git status --porcelain` ]]; then
        echo "1"
        git commit -am 'update docs' --null
        echo "2"
        git push -q
        echo "3"
        fi
        echo "4"
